/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppNovidadesRouteImport } from './routes/_app.novidades'
import { Route as AppLeadsAnalyticsRouteImport } from './routes/_app.leads-analytics'
import { Route as AppKanbanRouteImport } from './routes/_app.kanban'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCsRouteImport } from './routes/_app.cs'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppComercialRouteImport } from './routes/_app.comercial'
import { Route as AppAnalyticsChatRouteImport } from './routes/_app.analytics-chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppWhatsappIndexRouteImport } from './routes/_app.whatsapp.index'
import { Route as AppCsIndexRouteImport } from './routes/_app.cs.index'
import { Route as AppWhatsappTemplatesRouteImport } from './routes/_app.whatsapp.templates'
import { Route as AppWhatsappMetricasRouteImport } from './routes/_app.whatsapp.metricas'
import { Route as AppWhatsappIaRouteImport } from './routes/_app.whatsapp.ia'
import { Route as AppWhatsappFupsRouteImport } from './routes/_app.whatsapp.fups'
import { Route as AppWhatsappContasRouteImport } from './routes/_app.whatsapp.contas'
import { Route as AppWhatsappCampanhasRouteImport } from './routes/_app.whatsapp.campanhas'
import { Route as AppWhatsappAutomacoesRouteImport } from './routes/_app.whatsapp.automacoes'
import { Route as AppLeadIdRouteImport } from './routes/_app.lead.$id'
import { Route as AppCsSinaleiraPdaRouteImport } from './routes/_app.cs.sinaleira-pda'
import { Route as AppConfiguracoesHubspotRouteImport } from './routes/_app.configuracoes.hubspot'
import { Route as AppAnalyticsChatThreadIdRouteImport } from './routes/_app.analytics-chat.$threadId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicRdCallbackRouteImport } from './routes/api/public/rd/callback'
import { Route as ApiPublicHooksSyncRdRouteImport } from './routes/api/public/hooks/sync-rd'
import { Route as ApiPublicHooksSendWeeklyDigestRouteImport } from './routes/api/public/hooks/send-weekly-digest'
import { Route as ApiPublicHooksRunFupsRouteImport } from './routes/api/public/hooks/run-fups'
import { Route as ApiPublicHooksHubspotImportTickRouteImport } from './routes/api/public/hooks/hubspot-import-tick'
import { Route as AppWhatsappCampanhasIdRouteImport } from './routes/_app.whatsapp.campanhas.$id'
import { Route as ApiPublicWhatsappWebhookAccountIdRouteImport } from './routes/api/public/whatsapp/webhook.$accountId'
import { Route as ApiPublicWhatsappAutomationsTickRouteImport } from './routes/api/public/whatsapp/automations.tick'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppNovidadesRoute = AppNovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsAnalyticsRoute = AppLeadsAnalyticsRouteImport.update({
  id: '/leads-analytics',
  path: '/leads-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCsRoute = AppCsRouteImport.update({
  id: '/cs',
  path: '/cs',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComercialRoute = AppComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsChatRoute = AppAnalyticsChatRouteImport.update({
  id: '/analytics-chat',
  path: '/analytics-chat',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWhatsappIndexRoute = AppWhatsappIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppCsIndexRoute = AppCsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCsRoute,
} as any)
const AppWhatsappTemplatesRoute = AppWhatsappTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppWhatsappMetricasRoute = AppWhatsappMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppWhatsappIaRoute = AppWhatsappIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppWhatsappFupsRoute = AppWhatsappFupsRouteImport.update({
  id: '/fups',
  path: '/fups',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppWhatsappContasRoute = AppWhatsappContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppWhatsappCampanhasRoute = AppWhatsappCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppWhatsappAutomacoesRoute = AppWhatsappAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppWhatsappRoute,
} as any)
const AppLeadIdRoute = AppLeadIdRouteImport.update({
  id: '/lead/$id',
  path: '/lead/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCsSinaleiraPdaRoute = AppCsSinaleiraPdaRouteImport.update({
  id: '/sinaleira-pda',
  path: '/sinaleira-pda',
  getParentRoute: () => AppCsRoute,
} as any)
const AppConfiguracoesHubspotRoute = AppConfiguracoesHubspotRouteImport.update({
  id: '/hubspot',
  path: '/hubspot',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppAnalyticsChatThreadIdRoute =
  AppAnalyticsChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AppAnalyticsChatRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRdCallbackRoute = ApiPublicRdCallbackRouteImport.update({
  id: '/api/public/rd/callback',
  path: '/api/public/rd/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncRdRoute = ApiPublicHooksSyncRdRouteImport.update({
  id: '/api/public/hooks/sync-rd',
  path: '/api/public/hooks/sync-rd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendWeeklyDigestRoute =
  ApiPublicHooksSendWeeklyDigestRouteImport.update({
    id: '/api/public/hooks/send-weekly-digest',
    path: '/api/public/hooks/send-weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunFupsRoute = ApiPublicHooksRunFupsRouteImport.update({
  id: '/api/public/hooks/run-fups',
  path: '/api/public/hooks/run-fups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksHubspotImportTickRoute =
  ApiPublicHooksHubspotImportTickRouteImport.update({
    id: '/api/public/hooks/hubspot-import-tick',
    path: '/api/public/hooks/hubspot-import-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWhatsappCampanhasIdRoute = AppWhatsappCampanhasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWhatsappCampanhasRoute,
} as any)
const ApiPublicWhatsappWebhookAccountIdRoute =
  ApiPublicWhatsappWebhookAccountIdRouteImport.update({
    id: '/api/public/whatsapp/webhook/$accountId',
    path: '/api/public/whatsapp/webhook/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappAutomationsTickRoute =
  ApiPublicWhatsappAutomationsTickRouteImport.update({
    id: '/api/public/whatsapp/automations/tick',
    path: '/api/public/whatsapp/automations/tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analytics-chat': typeof AppAnalyticsChatRouteWithChildren
  '/comercial': typeof AppComercialRoute
  '/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/cs': typeof AppCsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/kanban': typeof AppKanbanRoute
  '/leads-analytics': typeof AppLeadsAnalyticsRoute
  '/novidades': typeof AppNovidadesRoute
  '/usuarios': typeof AppUsuariosRoute
  '/whatsapp': typeof AppWhatsappRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/analytics-chat/$threadId': typeof AppAnalyticsChatThreadIdRoute
  '/configuracoes/hubspot': typeof AppConfiguracoesHubspotRoute
  '/cs/sinaleira-pda': typeof AppCsSinaleiraPdaRoute
  '/lead/$id': typeof AppLeadIdRoute
  '/whatsapp/automacoes': typeof AppWhatsappAutomacoesRoute
  '/whatsapp/campanhas': typeof AppWhatsappCampanhasRouteWithChildren
  '/whatsapp/contas': typeof AppWhatsappContasRoute
  '/whatsapp/fups': typeof AppWhatsappFupsRoute
  '/whatsapp/ia': typeof AppWhatsappIaRoute
  '/whatsapp/metricas': typeof AppWhatsappMetricasRoute
  '/whatsapp/templates': typeof AppWhatsappTemplatesRoute
  '/cs/': typeof AppCsIndexRoute
  '/whatsapp/': typeof AppWhatsappIndexRoute
  '/whatsapp/campanhas/$id': typeof AppWhatsappCampanhasIdRoute
  '/api/public/hooks/hubspot-import-tick': typeof ApiPublicHooksHubspotImportTickRoute
  '/api/public/hooks/run-fups': typeof ApiPublicHooksRunFupsRoute
  '/api/public/hooks/send-weekly-digest': typeof ApiPublicHooksSendWeeklyDigestRoute
  '/api/public/hooks/sync-rd': typeof ApiPublicHooksSyncRdRoute
  '/api/public/rd/callback': typeof ApiPublicRdCallbackRoute
  '/api/public/whatsapp/automations/tick': typeof ApiPublicWhatsappAutomationsTickRoute
  '/api/public/whatsapp/webhook/$accountId': typeof ApiPublicWhatsappWebhookAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analytics-chat': typeof AppAnalyticsChatRouteWithChildren
  '/comercial': typeof AppComercialRoute
  '/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/kanban': typeof AppKanbanRoute
  '/leads-analytics': typeof AppLeadsAnalyticsRoute
  '/novidades': typeof AppNovidadesRoute
  '/usuarios': typeof AppUsuariosRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/analytics-chat/$threadId': typeof AppAnalyticsChatThreadIdRoute
  '/configuracoes/hubspot': typeof AppConfiguracoesHubspotRoute
  '/cs/sinaleira-pda': typeof AppCsSinaleiraPdaRoute
  '/lead/$id': typeof AppLeadIdRoute
  '/whatsapp/automacoes': typeof AppWhatsappAutomacoesRoute
  '/whatsapp/campanhas': typeof AppWhatsappCampanhasRouteWithChildren
  '/whatsapp/contas': typeof AppWhatsappContasRoute
  '/whatsapp/fups': typeof AppWhatsappFupsRoute
  '/whatsapp/ia': typeof AppWhatsappIaRoute
  '/whatsapp/metricas': typeof AppWhatsappMetricasRoute
  '/whatsapp/templates': typeof AppWhatsappTemplatesRoute
  '/cs': typeof AppCsIndexRoute
  '/whatsapp': typeof AppWhatsappIndexRoute
  '/whatsapp/campanhas/$id': typeof AppWhatsappCampanhasIdRoute
  '/api/public/hooks/hubspot-import-tick': typeof ApiPublicHooksHubspotImportTickRoute
  '/api/public/hooks/run-fups': typeof ApiPublicHooksRunFupsRoute
  '/api/public/hooks/send-weekly-digest': typeof ApiPublicHooksSendWeeklyDigestRoute
  '/api/public/hooks/sync-rd': typeof ApiPublicHooksSyncRdRoute
  '/api/public/rd/callback': typeof ApiPublicRdCallbackRoute
  '/api/public/whatsapp/automations/tick': typeof ApiPublicWhatsappAutomationsTickRoute
  '/api/public/whatsapp/webhook/$accountId': typeof ApiPublicWhatsappWebhookAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/analytics-chat': typeof AppAnalyticsChatRouteWithChildren
  '/_app/comercial': typeof AppComercialRoute
  '/_app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/_app/cs': typeof AppCsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/kanban': typeof AppKanbanRoute
  '/_app/leads-analytics': typeof AppLeadsAnalyticsRoute
  '/_app/novidades': typeof AppNovidadesRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/whatsapp': typeof AppWhatsappRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/analytics-chat/$threadId': typeof AppAnalyticsChatThreadIdRoute
  '/_app/configuracoes/hubspot': typeof AppConfiguracoesHubspotRoute
  '/_app/cs/sinaleira-pda': typeof AppCsSinaleiraPdaRoute
  '/_app/lead/$id': typeof AppLeadIdRoute
  '/_app/whatsapp/automacoes': typeof AppWhatsappAutomacoesRoute
  '/_app/whatsapp/campanhas': typeof AppWhatsappCampanhasRouteWithChildren
  '/_app/whatsapp/contas': typeof AppWhatsappContasRoute
  '/_app/whatsapp/fups': typeof AppWhatsappFupsRoute
  '/_app/whatsapp/ia': typeof AppWhatsappIaRoute
  '/_app/whatsapp/metricas': typeof AppWhatsappMetricasRoute
  '/_app/whatsapp/templates': typeof AppWhatsappTemplatesRoute
  '/_app/cs/': typeof AppCsIndexRoute
  '/_app/whatsapp/': typeof AppWhatsappIndexRoute
  '/_app/whatsapp/campanhas/$id': typeof AppWhatsappCampanhasIdRoute
  '/api/public/hooks/hubspot-import-tick': typeof ApiPublicHooksHubspotImportTickRoute
  '/api/public/hooks/run-fups': typeof ApiPublicHooksRunFupsRoute
  '/api/public/hooks/send-weekly-digest': typeof ApiPublicHooksSendWeeklyDigestRoute
  '/api/public/hooks/sync-rd': typeof ApiPublicHooksSyncRdRoute
  '/api/public/rd/callback': typeof ApiPublicRdCallbackRoute
  '/api/public/whatsapp/automations/tick': typeof ApiPublicWhatsappAutomationsTickRoute
  '/api/public/whatsapp/webhook/$accountId': typeof ApiPublicWhatsappWebhookAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analytics-chat'
    | '/comercial'
    | '/configuracoes'
    | '/cs'
    | '/dashboard'
    | '/financeiro'
    | '/kanban'
    | '/leads-analytics'
    | '/novidades'
    | '/usuarios'
    | '/whatsapp'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/analytics-chat/$threadId'
    | '/configuracoes/hubspot'
    | '/cs/sinaleira-pda'
    | '/lead/$id'
    | '/whatsapp/automacoes'
    | '/whatsapp/campanhas'
    | '/whatsapp/contas'
    | '/whatsapp/fups'
    | '/whatsapp/ia'
    | '/whatsapp/metricas'
    | '/whatsapp/templates'
    | '/cs/'
    | '/whatsapp/'
    | '/whatsapp/campanhas/$id'
    | '/api/public/hooks/hubspot-import-tick'
    | '/api/public/hooks/run-fups'
    | '/api/public/hooks/send-weekly-digest'
    | '/api/public/hooks/sync-rd'
    | '/api/public/rd/callback'
    | '/api/public/whatsapp/automations/tick'
    | '/api/public/whatsapp/webhook/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analytics-chat'
    | '/comercial'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/kanban'
    | '/leads-analytics'
    | '/novidades'
    | '/usuarios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/analytics-chat/$threadId'
    | '/configuracoes/hubspot'
    | '/cs/sinaleira-pda'
    | '/lead/$id'
    | '/whatsapp/automacoes'
    | '/whatsapp/campanhas'
    | '/whatsapp/contas'
    | '/whatsapp/fups'
    | '/whatsapp/ia'
    | '/whatsapp/metricas'
    | '/whatsapp/templates'
    | '/cs'
    | '/whatsapp'
    | '/whatsapp/campanhas/$id'
    | '/api/public/hooks/hubspot-import-tick'
    | '/api/public/hooks/run-fups'
    | '/api/public/hooks/send-weekly-digest'
    | '/api/public/hooks/sync-rd'
    | '/api/public/rd/callback'
    | '/api/public/whatsapp/automations/tick'
    | '/api/public/whatsapp/webhook/$accountId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/analytics-chat'
    | '/_app/comercial'
    | '/_app/configuracoes'
    | '/_app/cs'
    | '/_app/dashboard'
    | '/_app/financeiro'
    | '/_app/kanban'
    | '/_app/leads-analytics'
    | '/_app/novidades'
    | '/_app/usuarios'
    | '/_app/whatsapp'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/analytics-chat/$threadId'
    | '/_app/configuracoes/hubspot'
    | '/_app/cs/sinaleira-pda'
    | '/_app/lead/$id'
    | '/_app/whatsapp/automacoes'
    | '/_app/whatsapp/campanhas'
    | '/_app/whatsapp/contas'
    | '/_app/whatsapp/fups'
    | '/_app/whatsapp/ia'
    | '/_app/whatsapp/metricas'
    | '/_app/whatsapp/templates'
    | '/_app/cs/'
    | '/_app/whatsapp/'
    | '/_app/whatsapp/campanhas/$id'
    | '/api/public/hooks/hubspot-import-tick'
    | '/api/public/hooks/run-fups'
    | '/api/public/hooks/send-weekly-digest'
    | '/api/public/hooks/sync-rd'
    | '/api/public/rd/callback'
    | '/api/public/whatsapp/automations/tick'
    | '/api/public/whatsapp/webhook/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksHubspotImportTickRoute: typeof ApiPublicHooksHubspotImportTickRoute
  ApiPublicHooksRunFupsRoute: typeof ApiPublicHooksRunFupsRoute
  ApiPublicHooksSendWeeklyDigestRoute: typeof ApiPublicHooksSendWeeklyDigestRoute
  ApiPublicHooksSyncRdRoute: typeof ApiPublicHooksSyncRdRoute
  ApiPublicRdCallbackRoute: typeof ApiPublicRdCallbackRoute
  ApiPublicWhatsappAutomationsTickRoute: typeof ApiPublicWhatsappAutomationsTickRoute
  ApiPublicWhatsappWebhookAccountIdRoute: typeof ApiPublicWhatsappWebhookAccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/novidades': {
      id: '/_app/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof AppNovidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-analytics': {
      id: '/_app/leads-analytics'
      path: '/leads-analytics'
      fullPath: '/leads-analytics'
      preLoaderRoute: typeof AppLeadsAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cs': {
      id: '/_app/cs'
      path: '/cs'
      fullPath: '/cs'
      preLoaderRoute: typeof AppCsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comercial': {
      id: '/_app/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AppComercialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics-chat': {
      id: '/_app/analytics-chat'
      path: '/analytics-chat'
      fullPath: '/analytics-chat'
      preLoaderRoute: typeof AppAnalyticsChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp/': {
      id: '/_app/whatsapp/'
      path: '/'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof AppWhatsappIndexRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/_app/cs/': {
      id: '/_app/cs/'
      path: '/'
      fullPath: '/cs/'
      preLoaderRoute: typeof AppCsIndexRouteImport
      parentRoute: typeof AppCsRoute
    }
    '/_app/whatsapp/templates': {
      id: '/_app/whatsapp/templates'
      path: '/templates'
      fullPath: '/whatsapp/templates'
      preLoaderRoute: typeof AppWhatsappTemplatesRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/_app/whatsapp/metricas': {
      id: '/_app/whatsapp/metricas'
      path: '/metricas'
      fullPath: '/whatsapp/metricas'
      preLoaderRoute: typeof AppWhatsappMetricasRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/_app/whatsapp/ia': {
      id: '/_app/whatsapp/ia'
      path: '/ia'
      fullPath: '/whatsapp/ia'
      preLoaderRoute: typeof AppWhatsappIaRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/_app/whatsapp/fups': {
      id: '/_app/whatsapp/fups'
      path: '/fups'
      fullPath: '/whatsapp/fups'
      preLoaderRoute: typeof AppWhatsappFupsRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/_app/whatsapp/contas': {
      id: '/_app/whatsapp/contas'
      path: '/contas'
      fullPath: '/whatsapp/contas'
      preLoaderRoute: typeof AppWhatsappContasRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/_app/whatsapp/campanhas': {
      id: '/_app/whatsapp/campanhas'
      path: '/campanhas'
      fullPath: '/whatsapp/campanhas'
      preLoaderRoute: typeof AppWhatsappCampanhasRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/_app/whatsapp/automacoes': {
      id: '/_app/whatsapp/automacoes'
      path: '/automacoes'
      fullPath: '/whatsapp/automacoes'
      preLoaderRoute: typeof AppWhatsappAutomacoesRouteImport
      parentRoute: typeof AppWhatsappRoute
    }
    '/_app/lead/$id': {
      id: '/_app/lead/$id'
      path: '/lead/$id'
      fullPath: '/lead/$id'
      preLoaderRoute: typeof AppLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cs/sinaleira-pda': {
      id: '/_app/cs/sinaleira-pda'
      path: '/sinaleira-pda'
      fullPath: '/cs/sinaleira-pda'
      preLoaderRoute: typeof AppCsSinaleiraPdaRouteImport
      parentRoute: typeof AppCsRoute
    }
    '/_app/configuracoes/hubspot': {
      id: '/_app/configuracoes/hubspot'
      path: '/hubspot'
      fullPath: '/configuracoes/hubspot'
      preLoaderRoute: typeof AppConfiguracoesHubspotRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/_app/analytics-chat/$threadId': {
      id: '/_app/analytics-chat/$threadId'
      path: '/$threadId'
      fullPath: '/analytics-chat/$threadId'
      preLoaderRoute: typeof AppAnalyticsChatThreadIdRouteImport
      parentRoute: typeof AppAnalyticsChatRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rd/callback': {
      id: '/api/public/rd/callback'
      path: '/api/public/rd/callback'
      fullPath: '/api/public/rd/callback'
      preLoaderRoute: typeof ApiPublicRdCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-rd': {
      id: '/api/public/hooks/sync-rd'
      path: '/api/public/hooks/sync-rd'
      fullPath: '/api/public/hooks/sync-rd'
      preLoaderRoute: typeof ApiPublicHooksSyncRdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-weekly-digest': {
      id: '/api/public/hooks/send-weekly-digest'
      path: '/api/public/hooks/send-weekly-digest'
      fullPath: '/api/public/hooks/send-weekly-digest'
      preLoaderRoute: typeof ApiPublicHooksSendWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-fups': {
      id: '/api/public/hooks/run-fups'
      path: '/api/public/hooks/run-fups'
      fullPath: '/api/public/hooks/run-fups'
      preLoaderRoute: typeof ApiPublicHooksRunFupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/hubspot-import-tick': {
      id: '/api/public/hooks/hubspot-import-tick'
      path: '/api/public/hooks/hubspot-import-tick'
      fullPath: '/api/public/hooks/hubspot-import-tick'
      preLoaderRoute: typeof ApiPublicHooksHubspotImportTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp/campanhas/$id': {
      id: '/_app/whatsapp/campanhas/$id'
      path: '/$id'
      fullPath: '/whatsapp/campanhas/$id'
      preLoaderRoute: typeof AppWhatsappCampanhasIdRouteImport
      parentRoute: typeof AppWhatsappCampanhasRoute
    }
    '/api/public/whatsapp/webhook/$accountId': {
      id: '/api/public/whatsapp/webhook/$accountId'
      path: '/api/public/whatsapp/webhook/$accountId'
      fullPath: '/api/public/whatsapp/webhook/$accountId'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/automations/tick': {
      id: '/api/public/whatsapp/automations/tick'
      path: '/api/public/whatsapp/automations/tick'
      fullPath: '/api/public/whatsapp/automations/tick'
      preLoaderRoute: typeof ApiPublicWhatsappAutomationsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAnalyticsChatRouteChildren {
  AppAnalyticsChatThreadIdRoute: typeof AppAnalyticsChatThreadIdRoute
}

const AppAnalyticsChatRouteChildren: AppAnalyticsChatRouteChildren = {
  AppAnalyticsChatThreadIdRoute: AppAnalyticsChatThreadIdRoute,
}

const AppAnalyticsChatRouteWithChildren =
  AppAnalyticsChatRoute._addFileChildren(AppAnalyticsChatRouteChildren)

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesHubspotRoute: typeof AppConfiguracoesHubspotRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesHubspotRoute: AppConfiguracoesHubspotRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppCsRouteChildren {
  AppCsSinaleiraPdaRoute: typeof AppCsSinaleiraPdaRoute
  AppCsIndexRoute: typeof AppCsIndexRoute
}

const AppCsRouteChildren: AppCsRouteChildren = {
  AppCsSinaleiraPdaRoute: AppCsSinaleiraPdaRoute,
  AppCsIndexRoute: AppCsIndexRoute,
}

const AppCsRouteWithChildren = AppCsRoute._addFileChildren(AppCsRouteChildren)

interface AppWhatsappCampanhasRouteChildren {
  AppWhatsappCampanhasIdRoute: typeof AppWhatsappCampanhasIdRoute
}

const AppWhatsappCampanhasRouteChildren: AppWhatsappCampanhasRouteChildren = {
  AppWhatsappCampanhasIdRoute: AppWhatsappCampanhasIdRoute,
}

const AppWhatsappCampanhasRouteWithChildren =
  AppWhatsappCampanhasRoute._addFileChildren(AppWhatsappCampanhasRouteChildren)

interface AppWhatsappRouteChildren {
  AppWhatsappAutomacoesRoute: typeof AppWhatsappAutomacoesRoute
  AppWhatsappCampanhasRoute: typeof AppWhatsappCampanhasRouteWithChildren
  AppWhatsappContasRoute: typeof AppWhatsappContasRoute
  AppWhatsappFupsRoute: typeof AppWhatsappFupsRoute
  AppWhatsappIaRoute: typeof AppWhatsappIaRoute
  AppWhatsappMetricasRoute: typeof AppWhatsappMetricasRoute
  AppWhatsappTemplatesRoute: typeof AppWhatsappTemplatesRoute
  AppWhatsappIndexRoute: typeof AppWhatsappIndexRoute
}

const AppWhatsappRouteChildren: AppWhatsappRouteChildren = {
  AppWhatsappAutomacoesRoute: AppWhatsappAutomacoesRoute,
  AppWhatsappCampanhasRoute: AppWhatsappCampanhasRouteWithChildren,
  AppWhatsappContasRoute: AppWhatsappContasRoute,
  AppWhatsappFupsRoute: AppWhatsappFupsRoute,
  AppWhatsappIaRoute: AppWhatsappIaRoute,
  AppWhatsappMetricasRoute: AppWhatsappMetricasRoute,
  AppWhatsappTemplatesRoute: AppWhatsappTemplatesRoute,
  AppWhatsappIndexRoute: AppWhatsappIndexRoute,
}

const AppWhatsappRouteWithChildren = AppWhatsappRoute._addFileChildren(
  AppWhatsappRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsChatRoute: typeof AppAnalyticsChatRouteWithChildren
  AppComercialRoute: typeof AppComercialRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppCsRoute: typeof AppCsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppLeadsAnalyticsRoute: typeof AppLeadsAnalyticsRoute
  AppNovidadesRoute: typeof AppNovidadesRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppWhatsappRoute: typeof AppWhatsappRouteWithChildren
  AppLeadIdRoute: typeof AppLeadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsChatRoute: AppAnalyticsChatRouteWithChildren,
  AppComercialRoute: AppComercialRoute,
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppCsRoute: AppCsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppLeadsAnalyticsRoute: AppLeadsAnalyticsRoute,
  AppNovidadesRoute: AppNovidadesRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppWhatsappRoute: AppWhatsappRouteWithChildren,
  AppLeadIdRoute: AppLeadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksHubspotImportTickRoute: ApiPublicHooksHubspotImportTickRoute,
  ApiPublicHooksRunFupsRoute: ApiPublicHooksRunFupsRoute,
  ApiPublicHooksSendWeeklyDigestRoute: ApiPublicHooksSendWeeklyDigestRoute,
  ApiPublicHooksSyncRdRoute: ApiPublicHooksSyncRdRoute,
  ApiPublicRdCallbackRoute: ApiPublicRdCallbackRoute,
  ApiPublicWhatsappAutomationsTickRoute: ApiPublicWhatsappAutomationsTickRoute,
  ApiPublicWhatsappWebhookAccountIdRoute:
    ApiPublicWhatsappWebhookAccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
