/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppNovidadesRouteImport } from './routes/_app.novidades'
import { Route as AppKanbanRouteImport } from './routes/_app.kanban'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppLeadIdRouteImport } from './routes/_app.lead.$id'
import { Route as ApiPublicRdCallbackRouteImport } from './routes/api/public/rd/callback'
import { Route as ApiPublicHooksSyncRdRouteImport } from './routes/api/public/hooks/sync-rd'
import { Route as ApiPublicHooksSendWeeklyDigestRouteImport } from './routes/api/public/hooks/send-weekly-digest'
import { Route as ApiPublicWhatsappWebhookAccountIdRouteImport } from './routes/api/public/whatsapp/webhook.$accountId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppNovidadesRoute = AppNovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadIdRoute = AppLeadIdRouteImport.update({
  id: '/lead/$id',
  path: '/lead/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicRdCallbackRoute = ApiPublicRdCallbackRouteImport.update({
  id: '/api/public/rd/callback',
  path: '/api/public/rd/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncRdRoute = ApiPublicHooksSyncRdRouteImport.update({
  id: '/api/public/hooks/sync-rd',
  path: '/api/public/hooks/sync-rd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendWeeklyDigestRoute =
  ApiPublicHooksSendWeeklyDigestRouteImport.update({
    id: '/api/public/hooks/send-weekly-digest',
    path: '/api/public/hooks/send-weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookAccountIdRoute =
  ApiPublicWhatsappWebhookAccountIdRouteImport.update({
    id: '/api/public/whatsapp/webhook/$accountId',
    path: '/api/public/whatsapp/webhook/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/kanban': typeof AppKanbanRoute
  '/novidades': typeof AppNovidadesRoute
  '/usuarios': typeof AppUsuariosRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/lead/$id': typeof AppLeadIdRoute
  '/api/public/hooks/send-weekly-digest': typeof ApiPublicHooksSendWeeklyDigestRoute
  '/api/public/hooks/sync-rd': typeof ApiPublicHooksSyncRdRoute
  '/api/public/rd/callback': typeof ApiPublicRdCallbackRoute
  '/api/public/whatsapp/webhook/$accountId': typeof ApiPublicWhatsappWebhookAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/dashboard': typeof AppDashboardRoute
  '/kanban': typeof AppKanbanRoute
  '/novidades': typeof AppNovidadesRoute
  '/usuarios': typeof AppUsuariosRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/lead/$id': typeof AppLeadIdRoute
  '/api/public/hooks/send-weekly-digest': typeof ApiPublicHooksSendWeeklyDigestRoute
  '/api/public/hooks/sync-rd': typeof ApiPublicHooksSyncRdRoute
  '/api/public/rd/callback': typeof ApiPublicRdCallbackRoute
  '/api/public/whatsapp/webhook/$accountId': typeof ApiPublicWhatsappWebhookAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/kanban': typeof AppKanbanRoute
  '/_app/novidades': typeof AppNovidadesRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/lead/$id': typeof AppLeadIdRoute
  '/api/public/hooks/send-weekly-digest': typeof ApiPublicHooksSendWeeklyDigestRoute
  '/api/public/hooks/sync-rd': typeof ApiPublicHooksSyncRdRoute
  '/api/public/rd/callback': typeof ApiPublicRdCallbackRoute
  '/api/public/whatsapp/webhook/$accountId': typeof ApiPublicWhatsappWebhookAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/kanban'
    | '/novidades'
    | '/usuarios'
    | '/whatsapp'
    | '/lead/$id'
    | '/api/public/hooks/send-weekly-digest'
    | '/api/public/hooks/sync-rd'
    | '/api/public/rd/callback'
    | '/api/public/whatsapp/webhook/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/dashboard'
    | '/kanban'
    | '/novidades'
    | '/usuarios'
    | '/whatsapp'
    | '/lead/$id'
    | '/api/public/hooks/send-weekly-digest'
    | '/api/public/hooks/sync-rd'
    | '/api/public/rd/callback'
    | '/api/public/whatsapp/webhook/$accountId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/configuracoes'
    | '/_app/dashboard'
    | '/_app/kanban'
    | '/_app/novidades'
    | '/_app/usuarios'
    | '/_app/whatsapp'
    | '/_app/lead/$id'
    | '/api/public/hooks/send-weekly-digest'
    | '/api/public/hooks/sync-rd'
    | '/api/public/rd/callback'
    | '/api/public/whatsapp/webhook/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksSendWeeklyDigestRoute: typeof ApiPublicHooksSendWeeklyDigestRoute
  ApiPublicHooksSyncRdRoute: typeof ApiPublicHooksSyncRdRoute
  ApiPublicRdCallbackRoute: typeof ApiPublicRdCallbackRoute
  ApiPublicWhatsappWebhookAccountIdRoute: typeof ApiPublicWhatsappWebhookAccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/novidades': {
      id: '/_app/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof AppNovidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lead/$id': {
      id: '/_app/lead/$id'
      path: '/lead/$id'
      fullPath: '/lead/$id'
      preLoaderRoute: typeof AppLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/rd/callback': {
      id: '/api/public/rd/callback'
      path: '/api/public/rd/callback'
      fullPath: '/api/public/rd/callback'
      preLoaderRoute: typeof ApiPublicRdCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-rd': {
      id: '/api/public/hooks/sync-rd'
      path: '/api/public/hooks/sync-rd'
      fullPath: '/api/public/hooks/sync-rd'
      preLoaderRoute: typeof ApiPublicHooksSyncRdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-weekly-digest': {
      id: '/api/public/hooks/send-weekly-digest'
      path: '/api/public/hooks/send-weekly-digest'
      fullPath: '/api/public/hooks/send-weekly-digest'
      preLoaderRoute: typeof ApiPublicHooksSendWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook/$accountId': {
      id: '/api/public/whatsapp/webhook/$accountId'
      path: '/api/public/whatsapp/webhook/$accountId'
      fullPath: '/api/public/whatsapp/webhook/$accountId'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppNovidadesRoute: typeof AppNovidadesRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppLeadIdRoute: typeof AppLeadIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppNovidadesRoute: AppNovidadesRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppLeadIdRoute: AppLeadIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksSendWeeklyDigestRoute: ApiPublicHooksSendWeeklyDigestRoute,
  ApiPublicHooksSyncRdRoute: ApiPublicHooksSyncRdRoute,
  ApiPublicRdCallbackRoute: ApiPublicRdCallbackRoute,
  ApiPublicWhatsappWebhookAccountIdRoute:
    ApiPublicWhatsappWebhookAccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
